CREATE PROCEDURE KARDEX( IDART VARCHAR(13), IDALM VARCHAR(4), CIA SMALLINT )
RETURNS (
  CODIGO VARCHAR(13), FECHA DATE, FOLIO INTEGER, SERIE VARCHAR(20),
  ALM VARCHAR(4), COSTO FLOAT,
  PROVE VARCHAR(60), MODENT CHAR(1), NENTRADA INTEGER, COMPRA VARCHAR(60),
  FECSALE DATE, MODSAL CHAR(1)
) as
  DECLARE VARIABLE IDSERIE INTEGER;
  DECLARE VARIABLE IDNOMPRO INTEGER;
  DECLARE VARIABLE FECSAL DATE;
  DECLARE VARIABLE IDCOMPRO INTEGER;
  DECLARE VARIABLE SALIO CHAR(1);
  DECLARE VARIABLE IDALMVIENE VARCHAR(4);
  DECLARE VARIABLE FOLVIENE INTEGER;
  DECLARE VARIABLE IDALMHACIA VARCHAR(4);
  DECLARE VARIABLE FOLREC INTEGER;
  DECLARE VARIABLE NOMBRE_COMPRA VARCHAR(60);
  DECLARE VARIABLE NOMBRE_PRO VARCHAR(60);
  DECLARE VARIABLE CVEALM_VIENE VARCHAR(4);

BEGIN

  FOR SELECT CODIGO, ALMAC, FECHA, FOLIO, SERIE, NOMPRO,
    FECHASAL, NENTRADA, SALIO, VIENEDE, FOLVIENE, VAHACIA, FOLREC, MODENT, 
    COMPRO, MODSAL, COSTO
    FROM MOVART WHERE CODIGO = :CODIGO AND ALMAC = :ALMAC AND CIA=:CIA
    ORDER BY FOLIO;

  FOR SELEC_NOMALM SELECT CLAVE, NOMBRE FROM ALMACEN
       WHERE CLAVE = :CLAVE AND CIA= :CIA;

  FOR SELEC_CONCEP SELECT CONCEPTO FROM CONCEPS WHERE NCON = :NCON;

  FOR SELEC_MOVART  USING (IDART, IDALM, CIA)
     INTO ( CODIGO, ALM, FECHA, FOLIO, SERIE, IDNOMPRO,  FECSAL, NENTRADA, 
     SALIO, IDALMVIENE, FOLVIENE, IDALMHACIA, FOLREC, MODENT, IDCOMPRO, MODSAL, COSTO);
  DO
  BEGIN SQLSUCCESS LOOP
    IF SALIO = 'S' THEN
      IF FOLREC > 0 THEN
        EXEC SQL EXECUTE SELEC_NOMALM USING (IDALMHACIA, CIA) 
             INTO (CVEALM_VIENE, NOMBRE_PRO);
        EXEC SQL FETCH SELEC_NOMALM;
        COMPRA := CVEALM_VIENE + ' ' + NOMBRE_PRO + ' ' + CONVERT_CHAR(FOLREC);
      ELSE
        EXEC SQL EXECUTE SELEC_CONCEP USING (IDCOMPRO) INTO (COMPRA);
        EXEC SQL FETCH SELEC_CONCEP;
      END IF
      FECSALE := FECSAL;

    ELSE
      COMPRA := NULL;
      FECSALE := NULL;
      MODSAL := NULL;
    END IF
    IF FOLVIENE > 0 THEN
      EXEC SQL EXECUTE SELEC_NOMALM USING (IDALMVIENE, CIA) 
           INTO (CVEALM_VIENE, NOMBRE_PRO);
      EXEC SQL FETCH SELEC_NOMALM;
      PROVE := CVEALM_VIENE + ' ' + NOMBRE_PRO + ' ' + CONVERT_CHAR(FOLVIENE);
    ELSE
      EXEC SQL EXECUTE SELEC_CONCEP USING (IDNOMPRO) INTO (PROVE);
      EXEC SQL FETCH SELEC_CONCEP;
    END IF
    RETURN ROW;
    EXEC SQL FETCH SELEC_MOVART;
    SUSPEND;
  END
end;
